phpqa:
  analyzedDirs: ./
  buildDir: build/
  ignoredDirs:
    - vendor
    - build
    - cache
#  ignoredFiles: ""
  report: true
  execution: no-parallel
  output: file
  tools:
#    - phpcs
#    - php-cs-fixer
    - phpmd
#    - phpcpd
    - phpstan
#    - phpunit
    - psalm
#    - deptrac
  verbose: true
  extensions:
    - php

phpmd:
  standard: phpmd.ruleset.xml
  ignoreParsingErrors: true

psalm:
  config: ./psalm.xml
  deadCode: true

phpstan:
  level: 8
  standard: ./phpstan.neon.dist