runner:
  phpstan:
    cmd: vendor/bin/phpstan --error-format=raw --no-progress --no-interaction
    format: phpstan
    name: phpstan
    level: warning

  psalm:
    cmd: vendor/bin/psalm --config=psalm.xml --no-progress --output-format=text
    format: psalm
    name: psalm
    level: warning
