runner:
  phpmd:
    cmd: phpmd . checkstyle phpmd.ruleset.xml --exclude 'cache/,vendor/' --baseline-file phpmd.baseline.xml
    name: phpmd
    format: checkstyle
    level: warning

  php-cs-fixer:
    cmd: php-cs-fixer fix --dry-run --format=checkstyle
    format: checkstyle
    name: php-cs-fixer
    level: warning

  phpstan:
    cmd: ./vendor/bin/phpstan --error-format=checkstyle
    format: checkstyle
    name: phpstan
    level: warning

  psalm:
    cmd: psalm --config=psalm.xml --no-progress --use-baseline=psalm-baseline.xml --output-format=checkstyle
    format: checkstyle
    name: psalm
    level: warning