runner:
  # phpmd:
  #   cmd: vendor/bin/phpmd . checkstyle phpmd.ruleset.xml --exclude 'cache/*,vendor/*' --baseline-file phpmd.baseline.xml
  #   name: phpmd
  #   format: checkstyle
  #   level: warning

  # phpstan:
  #   cmd: vendor/bin/phpstan --error-format=checkstyle
  #   format: checkstyle
  #   name: phpstan
  #   level: warning

  psalm:
    cmd: psalm --config=psalm.xml --no-progress --output-format=text
    format: psalm
    name: psalm
    level: warning
