runner:
  phpmd:
    cmd: phpmd . checkstyle phpmd.ruleset.xml --exclude 'cache/*,vendor/*' --baseline-file phpmd.baseline.xml
    name: phpmd
    format: checkstyle
    level: warning

  phpstan:
    cmd: phpstan --error-format=checkstyle
    format: checkstyle
    name: phpstan
    level: warning

  psalm:
    cmd: psalm --config=psalm.xml --no-progress --use-baseline=psalm-baseline.xml --output-format=checkstyle
    format: checkstyle
    name: psalm
    level: warning