runner:
  phpmd:
    cmd: phpmd . github phpmd.ruleset.xml --exclude 'cache/,vendor/' --baseline-file phpmd.baseline.xml
    name: phpmd
    errorformat:
      - "%.%#%*[\ ]file=%f,line=%l::%m"
    level: warning

  phpstan:
    cmd: ./vendor/bin/phpstan --error-format=raw
    format: phpstan
    name: phpstan
    level: warning

  psalm:
    cmd: psalm --config=psalm.xml --use-baseline=psalm-baseline.xml --output-format=text
    format: psalm
    name: psalm
    level: warning