name: QA

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - master
      - develop

jobs:
  qa:
    container: zdenekdrahos/phpqa
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # composer is not necessary, if you are not running phpunit/psalm/phpstan
      - name: Cache composer
        uses: actions/cache@v2
        with:
          path: |
            ~/.composer/cache
            vendor
          key: php-composer-$
          restore-keys: "php-composer-74"

      - name: Install dependencies
        run: |
          composer install --no-interaction --no-progress --ignore-platform-reqs;

      - name: phpqa
        run: composer run-script phpqa

      - name: Upload QA files
        uses: actions/upload-artifact@v2
        with:
          name: phpqa
          path: build
