name: phpQA

on:
  - push
  - pull_request

jobs:
  qa:
    container: zdenekdrahos/phpqa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # composer is not necessary, if you are not running phpunit/psalm/phpstan
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: |
          composer install --no-interaction --no-progress --ignore-platform-reqs;

      - name: Run phpQA
        run: composer run-script phpqa

      - name: Upload QA files
        uses: actions/upload-artifact@v2
        with:
          name: phpqa
          path: build
