name: PHPMD
on: [push, pull_request]

jobs:
  phpmd:
    name: phpmd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: igbinary
          coverage: none
          tools: phpmd, psalm

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress -o

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Reviewdog GitHub Check
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: reviewdog -reporter=github-check -filter-mode=nofilter -fail-on-error=true -tee

#      - name: PHPMD
#        run: 'phpmd . github phpmd.ruleset.xml --exclude "build/,vendor/"'

#      - name: Psalm
#        run: 'psalm --config=psalm.xml --show-info=true --stats --no-progress --use-baseline=psalm-baseline.xml --output-format=github'